# Generated by Django 4.0.3 on 2022-03-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0004_alter_student_father_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='father_first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(to='register_app.parent'),
        ),
    ]
