# Generated by Django 4.0.3 on 2022-04-09 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register_app', '0005_remove_student_father_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='name_of_class',
            field=models.CharField(choices=[('0', 'NIEPRZYPISANA'), ('1', '1A'), ('2', '1B'), ('3', '1C'), ('4', '2A'), ('5', '2B')], default=0, max_length=2),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=64)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register_app.teacher'),
        ),
    ]
