# Generated by Django 4.0.3 on 2022-04-18 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0006_schoolclass_name_of_class_teacher_schoolclass_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='name_of_class',
            field=models.CharField(default='NIEPRZYPISANE', max_length=2),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=32, verbose_name='Imię (imiona)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Nazwisko'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Biologia'), (2, 'Geografia'), (3, 'Fizyka'), (4, 'Chemia'), (5, 'Matematyka'), (6, 'Język Polski'), (7, 'Język angielski')], default='nieprzypisane', max_length=1)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.schoolclass')),
                ('teacher', models.ForeignKey(default='nieprzypisany', on_delete=django.db.models.deletion.SET_DEFAULT, to='register_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_hour', models.DateTimeField()),
                ('ending_hour', models.DateTimeField()),
                ('topic', models.CharField(max_length=64)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(choices=[(1, '1'), (1.5, '1+'), (1.75, '2-'), (2, '2'), (2.5, '2+'), (2.75, '3-'), (3, '3'), (3.5, '3+'), (3.75, '4-'), (4, '4'), (4.5, '4+'), (4.75, '5-'), (5, '5'), (5.5, '5+'), (5.75, '6-'), (6, '6')])),
                ('description', models.CharField(max_length=32)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.student')),
            ],
        ),
    ]
