# Generated by Django 4.0.3 on 2022-04-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0007_alter_schoolclass_name_of_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.IntegerField(choices=[(1, 'Biologia'), (2, 'Geografia'), (3, 'Fizyka'), (4, 'Chemia'), (5, 'Matematyka'), (6, 'Język Polski'), (7, 'Język angielski')], default='nieprzypisane'),
        ),
    ]
