# Generated by Django 4.0.3 on 2022-04-18 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0008_alter_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='name_of_class',
            field=models.CharField(default='NIEPRZYPISANE', max_length=2, verbose_name='symbol'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register_app.teacher', verbose_name='wychowawca'),
        ),
    ]
