# Generated by Django 4.0.3 on 2022-04-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0009_alter_schoolclass_name_of_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='grade',
            field=models.CharField(max_length=2),
        ),
    ]
