# Generated by Django 4.0.3 on 2022-04-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0010_alter_grades_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': (('can_create_lessons', 'Provides possibility to create new lessons'), ('can_set_attendance', 'Provides possibility to check attendance'), ('can_set_grades', 'Provides possibility to set grades'))},
        ),
    ]
