# Generated by Django 4.0.3 on 2022-04-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0011_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('can_view_grades', 'can view grades'),)},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': (('can_create_lessons', 'Provides possibility to create new lessons'), ('can_set_attendance', 'Provides possibility to check attendance'), ('can_set_grades', 'Provides possibility to set grades'), ('can_view_grades', 'Can view grades'))},
        ),
    ]
